from django.test import TestCase

# Create your tests here.

# CREATE A POOL OF USERS
# ADD THEM TO A GROUP
# ADD THEM TO A ROTATION FOR M-F FROM 8-5
# CREATE AND ASSOCIATE A BUNDLE TO THE ROTATION
# LOOK FOR WARNING ON BUNDLE DETAIL VIEW NOTING THAT COVERAGE IS NOT COMPLETE
