# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RotationsInBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Order in the rotation')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncall.Bundle')),
            ],
        ),
        migrations.RemoveField(
            model_name='rotation',
            name='order',
        ),
        migrations.AlterField(
            model_name='contactpreference',
            name='start_time',
            field=models.IntegerField(choices=[[0, '12 am'], [1, '1 am'], [2, '2 am'], [3, '3 am'], [4, '4 am'], [5, '5 am'], [6, '6 am'], [7, '7 am'], [8, '8 am'], [9, '9 am'], [10, '10 am'], [11, '11 am'], [12, '12 pm'], [13, '1 pm'], [14, '2 pm'], [15, '3 pm'], [16, '4 pm'], [17, '5 pm'], [18, '6 pm'], [19, '7 pm'], [20, '8 pm'], [21, '9 pm'], [22, '10 pm'], [23, '11 pm']], help_text='Hour in the Day'),
        ),
        migrations.AlterField(
            model_name='contactpreference',
            name='stop_time',
            field=models.IntegerField(choices=[[0, '12 am'], [1, '1 am'], [2, '2 am'], [3, '3 am'], [4, '4 am'], [5, '5 am'], [6, '6 am'], [7, '7 am'], [8, '8 am'], [9, '9 am'], [10, '10 am'], [11, '11 am'], [12, '12 pm'], [13, '1 pm'], [14, '2 pm'], [15, '3 pm'], [16, '4 pm'], [17, '5 pm'], [18, '6 pm'], [19, '7 pm'], [20, '8 pm'], [21, '9 pm'], [22, '10 pm'], [23, '11 pm']], help_text='Hour in the Day'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='length',
            field=models.IntegerField(verbose_name='Users to be contacted before escalation. Set to zero if primary is always set.'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='start_time',
            field=models.IntegerField(choices=[[0, '12 am'], [1, '1 am'], [2, '2 am'], [3, '3 am'], [4, '4 am'], [5, '5 am'], [6, '6 am'], [7, '7 am'], [8, '8 am'], [9, '9 am'], [10, '10 am'], [11, '11 am'], [12, '12 pm'], [13, '1 pm'], [14, '2 pm'], [15, '3 pm'], [16, '4 pm'], [17, '5 pm'], [18, '6 pm'], [19, '7 pm'], [20, '8 pm'], [21, '9 pm'], [22, '10 pm'], [23, '11 pm']], help_text='Hour in the Day'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='stop_time',
            field=models.IntegerField(choices=[[0, '12 am'], [1, '1 am'], [2, '2 am'], [3, '3 am'], [4, '4 am'], [5, '5 am'], [6, '6 am'], [7, '7 am'], [8, '8 am'], [9, '9 am'], [10, '10 am'], [11, '11 am'], [12, '12 pm'], [13, '1 pm'], [14, '2 pm'], [15, '3 pm'], [16, '4 pm'], [17, '5 pm'], [18, '6 pm'], [19, '7 pm'], [20, '8 pm'], [21, '9 pm'], [22, '10 pm'], [23, '11 pm']], help_text='Hour in the Day'),
        ),
        migrations.AddField(
            model_name='rotationsinbundle',
            name='rotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncall.Rotation'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='rotations',
            field=models.ManyToManyField(through='oncall.RotationsInBundle', to='oncall.Rotation'),
        ),
    ]
